server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ubp
    username: postgres
    password: Gaurav@01postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    issuer: ubp
    access-token-minutes: 15
    refresh-token-days: 7
    secret: "change_this_secret_to_a_long_random_value"
  cors:
    allowed-origins:
      - "http://localhost:5173"
